Fixed the auto comment on PR merge workflow (#1144)

diff --git a/.github/workflows/pr-merge-comment.yml b/.github/workflows/pr-merge-comment.yml
--- a/.github/workflows/pr-merge-comment.yml
+++ b/.github/workflows/pr-merge-comment.yml
@@ -1,8 +1,12 @@
 name: Auto Comment on PR Merge
 
 on:
-  pull_request:
+  pull_request_target:
     types: [closed]
+
+permissions:
+  issues: write
+  pull-requests: write
 
 jobs:
   comment:
@@ -14,8 +18,20 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
-        curl -X POST \
+        COMMENT=$(cat <<EOF
+        {
+          "body": "Congrats, Your pull request has been successfully merged 🥳🎉 @${{ github.event.pull_request.user.login }} !! Thank you for your contribution to my project. 🚀 Keep Contributing!! ✨"
+        }
+        EOF
+        )
+        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
+          -X POST \
           -H "Authorization: token $GITHUB_TOKEN" \
           -H "Accept: application/vnd.github.v3+json" \
-          -d '{"body":"🎉 Your pull request has been successfully merged! 🎉 Thank you for your contribution to our project. Your efforts are greatly appreciated. Keep Contributing!! 🚀"}' \
-          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
+          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
+          -d "$COMMENT")
+        cat response.json
+        if [ "$RESPONSE" -ne 201 ]; then
+          echo "Failed to add comment"
+          exit 1
+        fi
